version: '3.4'

services:
  redis-ioc:
    image: dockerregistry.lnls-sirius.com.br/iot/redis-ioc:26-07
    networks:
      - hostnet
    build:  
      dockerfile: 'Dockerfile'
      context: .
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname != TA-TiRack-CO-FWSrv-1
          - node.hostname == CA-RaTim-CO-IOCSrv
          - node.hostname != IA-14RaDiag03-CO-IOCSrv
          - node.hostname != IA-16RaBbB-CO-IOCSrv
          - node.hostname != IA-18RaDiag04-CO-IOCSrv
          - node.hostname != IA-20RaDiag01-CO-IOCSrv-1
          - node.hostname != IA-20RaDiag01-CO-IOCSrv-2
          - node.hostname != IA-20RaDiag02-CO-IOCSrv-1
          - node.hostname != IA-20RaDiag02-CO-IOCSrv-2
      restart_policy:
        condition: any
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  hostnet:
    external:
      name: "host"