run: 
	# wget https://gitlab.cnpem.br/con/redis-ioc/raw/master/scripts/spreadsheet/Redes%20e%20Beaglebones.xlsx -O "spreadsheet/Redes e Beaglebones.xlsx"
	python3 ./generate.py
	bash -c 'set -x; set -e; source functions; run'